### ISSUE TITLE
quic http/3 support

### ISSUE THREAD

**Issue by lavacano** [knyzorg/nginx-pagespeed#1]
any chance?

https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche

**Comment by vezaynk** [comment]
This project powers production webservers, so I'm wary of adding a module that Cloudflare themselves describe as experimental. NGINX will eventually ship HTTP3 themselves so I'm inclined to wait for that.

https://www.nginx.com/blog/our-roadmap-quic-http-3-support-nginx/ 

This project should be pretty easy to fork if you need Quiche specifically.
